"""Примеры тел запросов для OpenAPI и Pydantic-схем (ядро, без зависимости от api)."""

# Синхронизировано с examples/single_predict_request.json
TRIP_FEATURES_EXAMPLE: dict = {
    "user_age": 24,
    "driving_experience_years": 3.0,
    "account_age_days": 14,
    "payment_delay_count": 1,
    "previous_incidents_count": 0,
    "rating": 3.2,
    "tariff_type": "economy",
    "trip_duration_min": 45.0,
    "trip_distance_km": 18.5,
    "average_speed_kmh": 28.0,
    "max_speed_kmh": 125.0,
    "start_hour": 23,
    "day_of_week": 5,
    "trip_cost": 420.0,
    "late_finish_flag": 1,
    "trip_start_zone": "center",
    "trip_end_zone": "north",
    "car_category": "sedan",
    "car_age_years": 4.0,
    "mileage_km": 95000.0,
    "fuel_or_charge_level_start": 78.0,
    "fuel_or_charge_level_end": 62.0,
    "weather_condition": "rain",
    "traffic_level": "high",
    "city_zone_risk": "high",
    "night_trip_flag": 1,
    "weekend_flag": 1,
}

BATCH_PREDICT_EXAMPLE: dict = {
    "items": [
        TRIP_FEATURES_EXAMPLE,
        {
            "user_age": 35,
            "driving_experience_years": 12.0,
            "account_age_days": 400,
            "payment_delay_count": 0,
            "previous_incidents_count": 0,
            "rating": 4.7,
            "tariff_type": "standard",
            "trip_duration_min": 22.0,
            "trip_distance_km": 8.0,
            "average_speed_kmh": 22.0,
            "max_speed_kmh": 65.0,
            "start_hour": 14,
            "day_of_week": 2,
            "trip_cost": 180.0,
            "late_finish_flag": 0,
            "trip_start_zone": "south",
            "trip_end_zone": "south",
            "car_category": "compact",
            "car_age_years": 2.0,
            "mileage_km": 45000.0,
            "fuel_or_charge_level_start": 90.0,
            "fuel_or_charge_level_end": 85.0,
            "weather_condition": "clear",
            "traffic_level": "low",
            "city_zone_risk": "low",
            "night_trip_flag": 0,
            "weekend_flag": 0,
        },
    ]
}
